AWSTemplateFormatVersion: '2010-09-09'
Description: Production-ready RDS PostgreSQL with Multi-AZ

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]

  DBInstanceClass:
    Type: String
    Default: db.t3.medium
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.r6g.large
      - db.r6g.xlarge

  DBName:
    Type: String
    Default: appdb
    MinLength: 1
    MaxLength: 64

  MasterUsername:
    Type: String
    Default: admin
    MinLength: 1
    MaxLength: 16

  MasterUserPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41

  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least 2 subnets in different AZs

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Resources:
  # Security Group
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/8
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-rds-sg

  # Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Subnet Group
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-rds-subnet-group

  # Parameter Group
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: postgres15
      Description: Custom parameter group
      Parameters:
        log_statement: all
        log_min_duration_statement: 1000
        shared_preload_libraries: pg_stat_statements

  # RDS Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${Environment}-${DBName}
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '15.4'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp3
      StorageEncrypted: true
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      MultiAZ: !If [IsProduction, true, false]
      PubliclyAccessible: false
      BackupRetentionPeriod: !If [IsProduction, 7, 1]
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: Mon:04:00-Mon:05:00
      EnablePerformanceInsights: !If [IsProduction, true, false]
      PerformanceInsightsRetentionPeriod: !If [IsProduction, 7, 7]
      DeletionProtection: !If [IsProduction, true, false]
      CopyTagsToSnapshot: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DBEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${Environment}-DBEndpoint

  DBPort:
    Description: RDS Port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${Environment}-DBPort

  ConnectionString:
    Description: PostgreSQL Connection String
    Value: !Sub postgresql://${MasterUsername}:PASSWORD@${DBInstance.Endpoint.Address}:${DBInstance.Endpoint.Port}/${DBName}
